### ISSUE TITLE
Rename to broccoli-es2015modules?

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/broccoli-es6modules#9]
Obviously, broccoli-es2015modules is dumb, but should we rename?

**Comment by ef4** [comment]
:-1:

**Comment by mkoxio** [comment]
es2015 is just dumb. same as preferring @me.com instead of @icloud.com that same mistake apple made

**Comment by trek** [comment]
:-1: regardless of official designation, I think the majority of people will continue to use "ES6"
